import { fileURLToPath } from "node:url";
import { z } from "zod";
import { readJson } from "../_shared/json";
import { AppCategoryLabelSchema, GameCategoryLabelSchema } from "./category";

const LLM_CLASSIFICATIONS_PATH = fileURLToPath(
  new URL("../../../config/llm-classifications.json", import.meta.url),
);

/**
 * One LLM-assigned category for a single app the deterministic signals
 * (upstream categories, distro sections, name patterns, description
 * keywords) couldn't classify. Keyed by the app's own `CatalogApp.id` —
 * not a name glob like `category-rules.json` — because the LLM classifies
 * each *app* individually, and an id (already unique and stable across
 * rebuilds) avoids the generic-name collision trap a bare-name key would
 * reintroduce (see `match/group.ts`'s GENERIC_NAME_BLOCKLIST).
 *
 * `category` is a union of the two disjoint taxonomies: an app label for
 * non-game apps, a game genre for games. The generating script
 * (`scripts/classify-llm.ts`) always emits the type consistent with each
 * app's own `contentType`, so a lookup never returns a genre for an app
 * or vice versa.
 */
const LlmClassificationEntrySchema = z.object({
  id: z
    .string()
    .describe("The CatalogApp id this category was assigned to, e.g. 'pacman-aur:wings3d'."),
  category: z
    .union([AppCategoryLabelSchema, GameCategoryLabelSchema])
    .describe(
      "The assigned label — an app category or a game genre, consistent with the app's contentType.",
    ),
  confidence: z
    .enum(["high", "medium", "low"])
    .describe(
      "The LLM's own certainty in this category. A three-level enum rather than a numeric score — self-reported LLM probabilities are poorly calibrated, so a finer scale would only pretend to precision. 'low' entries are kept for auditability but never applied (see llmCategoryMap).",
    ),
  reason: z.string().describe("Why the LLM assigned this category — for auditability."),
  model: z
    .string()
    .describe(
      "The Gemini model that produced this entry, e.g. 'gemini-3.8-flash' — classify-llm rotates across models to spread the free tier's per-model daily quota, so quality can be audited per model.",
    ),
});

/** Entries at this confidence stay "To Classify" — a wrong category is worse than an honest unknown. */
const UNAPPLIED_CONFIDENCE = "low";

export type LlmClassificationEntry = z.infer<typeof LlmClassificationEntrySchema>;

export const LlmClassificationsListSchema = z.array(LlmClassificationEntrySchema).meta({
  title: "Enrich: LLM classifications",
  description:
    "LLM-assigned categories for apps the deterministic signals couldn't classify — checked last in pickCategoryLabel, just before the 'To Classify' fallback. Generated by `pnpm classify-llm` (Gemini API), committed and consumed at build time; never hand-edited.",
});

/** Loads the LLM classification list (`config/llm-classifications.json`, missing file reads as empty). */
export function loadLlmClassifications(): LlmClassificationEntry[] {
  return readJson(LLM_CLASSIFICATIONS_PATH, LlmClassificationsListSchema);
}

/** A fast id → category label lookup built once per enrich pass, so the per-app fallback is O(1). Skips low-confidence entries — see `UNAPPLIED_CONFIDENCE`. */
export function llmCategoryMap(entries: LlmClassificationEntry[]): Map<string, string> {
  return new Map(
    entries
      .filter((entry) => entry.confidence !== UNAPPLIED_CONFIDENCE)
      .map((entry) => [entry.id, entry.category]),
  );
}

/**
 * Looks up an app's LLM-assigned category, but only returns it if it still
 * matches the app's *current* isGame taxonomy (an app label for a non-game,
 * a genre for a game). The stored entry is only guaranteed consistent with
 * contentType at generation time (see `LlmClassificationEntrySchema`'s doc
 * comment) — a later change to the deterministic isGame signals (tightened
 * or loosened without rerunning `pnpm classify-llm`) can flip an app's
 * isGame without regenerating `config/llm-classifications.json`, which
 * would otherwise leak a stale genre label onto a non-game app or vice
 * versa instead of falling back to `TO_CLASSIFY`.
 */
export function pickLlmCategory(
  map: Map<string, string>,
  id: string,
  isGame: boolean,
): string | undefined {
  const category = map.get(id);
  if (category === undefined) return undefined;
  const schema = isGame ? GameCategoryLabelSchema : AppCategoryLabelSchema;
  return schema.safeParse(category).success ? category : undefined;
}
