import { fileURLToPath } from "node:url";
import { z } from "zod";
import { readJson } from "../_shared/json";
import { AppCategoryLabelSchema, GameCategoryLabelSchema } from "./category";

const LLM_CLASSIFICATIONS_PATH = fileURLToPath(
  new URL("../../../config/llm-classifications.json", import.meta.url),
);

/**
 * One LLM-assigned category for a single app the deterministic signals
 * (upstream categories, distro sections, name patterns, description
 * keywords) couldn't classify. Keyed by the app's own `CatalogApp.id` —
 * not a name glob like `category-rules.json` — because the LLM classifies
 * each *app* individually, and an id (already unique and stable across
 * rebuilds) avoids the generic-name collision trap a bare-name key would
 * reintroduce (see `match/group.ts`'s GENERIC_NAME_BLOCKLIST).
 *
 * `category` is a union of the two disjoint taxonomies: an app label for
 * non-game apps, a game genre for games. The label itself carries the
 * LLM's verdict on whether the package is a game at all: the generating
 * script (`scripts/classify-llm.ts`) offers both taxonomies for every app,
 * and `pickLlmClassification` derives `contentType` from which one the
 * answer belongs to — the deterministic isGame heuristics can't override
 * it (they already had their say: only apps they left in "To Classify"
 * reach the LLM).
 */
const LlmClassificationEntrySchema = z.object({
  id: z
    .string()
    .describe("The CatalogApp id this category was assigned to, e.g. 'pacman-aur:wings3d'."),
  category: z
    .union([AppCategoryLabelSchema, GameCategoryLabelSchema])
    .describe(
      "The assigned label — an app category or a game genre, consistent with the app's contentType.",
    ),
  confidence: z
    .enum(["high", "medium", "low"])
    .describe(
      "The LLM's own certainty in this category. A three-level enum rather than a numeric score — self-reported LLM probabilities are poorly calibrated, so a finer scale would only pretend to precision. 'low' entries are kept for auditability but never applied (see llmCategoryMap).",
    ),
  reason: z.string().describe("Why the LLM assigned this category — for auditability."),
  model: z
    .string()
    .describe(
      "The model that produced this entry, e.g. 'gemini-3.8-flash' or 'openai/gpt-oss-20b' — classify-llm rotates across config/llm-models.json's models to spread their free tiers' per-model quotas, so quality can be audited per model.",
    ),
});

/** Entries at this confidence stay "To Classify" — a wrong category is worse than an honest unknown. */
const UNAPPLIED_CONFIDENCE = "low";

export type LlmClassificationEntry = z.infer<typeof LlmClassificationEntrySchema>;

export const LlmClassificationsListSchema = z.array(LlmClassificationEntrySchema).meta({
  title: "Enrich: LLM classifications",
  description:
    "LLM-assigned categories for apps the deterministic signals couldn't classify — checked last in pickCategoryLabel, just before the 'To Classify' fallback. Generated by `pnpm classify-llm` (free-tier LLMs, see config/llm-models.json), committed and consumed at build time; never hand-edited.",
});

/** Loads the LLM classification list (`config/llm-classifications.json`, missing file reads as empty). */
export function loadLlmClassifications(): LlmClassificationEntry[] {
  return readJson(LLM_CLASSIFICATIONS_PATH, LlmClassificationsListSchema);
}

/** A fast id → category label lookup built once per enrich pass, so the per-app fallback is O(1). Skips low-confidence entries — see `UNAPPLIED_CONFIDENCE`. */
export function llmCategoryMap(entries: LlmClassificationEntry[]): Map<string, string> {
  return new Map(
    entries
      .filter((entry) => entry.confidence !== UNAPPLIED_CONFIDENCE)
      .map((entry) => [entry.id, entry.category]),
  );
}

/** What an applied LLM entry decides for an app: its category label, and — implied by which taxonomy that label belongs to — whether it's a game. */
export interface LlmClassification {
  category: string;
  isGame: boolean;
}

/**
 * Looks up an app's LLM-assigned classification. The label's taxonomy is
 * the LLM's own game-or-app verdict (see `LlmClassificationEntrySchema`),
 * so it's returned as `isGame` for the caller to apply — an entry is never
 * rejected for disagreeing with the deterministic isGame signals, which
 * is the whole point of asking the LLM about the apps those signals
 * couldn't place. Returns undefined for an unknown id or a label outside
 * both taxonomies (a stale entry after a taxonomy change).
 */
export function pickLlmClassification(
  map: Map<string, string>,
  id: string,
): LlmClassification | undefined {
  const category = map.get(id);
  if (category === undefined) return undefined;
  if (GameCategoryLabelSchema.safeParse(category).success) return { category, isGame: true };
  if (AppCategoryLabelSchema.safeParse(category).success) return { category, isGame: false };
  return undefined;
}
