import { fileURLToPath } from "node:url";
import { z } from "zod";
import { readJson } from "../_shared/json";
import { AppCategoryLabelSchema, GameCategoryLabelSchema } from "./category";

const LLM_CLASSIFICATIONS_PATH = fileURLToPath(
  new URL("../../../config/llm-classifications.json", import.meta.url),
);

/**
 * One LLM-assigned category for a single app the deterministic signals
 * (upstream categories, distro sections, name patterns, description
 * keywords) couldn't classify. Keyed by the app's own `CatalogApp.id` —
 * not a name glob like `category-rules.json` — because the LLM classifies
 * each *app* individually, and an id (already unique and stable across
 * rebuilds) avoids the generic-name collision trap a bare-name key would
 * reintroduce (see `match/group.ts`'s GENERIC_NAME_BLOCKLIST).
 *
 * `category` is a union of the two disjoint taxonomies: an app label for
 * non-game apps, a game genre for games. The generating script
 * (`scripts/classify-llm.ts`) always emits the type consistent with each
 * app's own `contentType`, so a lookup never returns a genre for an app
 * or vice versa.
 */
const LlmClassificationEntrySchema = z.object({
  id: z.string().describe("The CatalogApp id this category was assigned to, e.g. 'pacman-aur:wings3d'."),
  category: z
    .union([AppCategoryLabelSchema, GameCategoryLabelSchema])
    .describe("The assigned label — an app category or a game genre, consistent with the app's contentType."),
  reason: z.string().describe("Why the LLM assigned this category — for auditability."),
});

export type LlmClassificationEntry = z.infer<typeof LlmClassificationEntrySchema>;

export const LlmClassificationsListSchema = z.array(LlmClassificationEntrySchema).meta({
  title: "Enrich: LLM classifications",
  description:
    "LLM-assigned categories for apps the deterministic signals couldn't classify — checked last in pickCategoryLabel, just before the 'To Classify' fallback. Generated by `pnpm classify-llm` (Gemini API), committed and consumed at build time; never hand-edited.",
});

/** Loads the LLM classification list (`config/llm-classifications.json`, missing file reads as empty). */
export function loadLlmClassifications(): LlmClassificationEntry[] {
  return readJson(LLM_CLASSIFICATIONS_PATH, LlmClassificationsListSchema);
}

/** A fast id → category label lookup built once per enrich pass, so the per-app fallback is O(1). */
export function llmCategoryMap(entries: LlmClassificationEntry[]): Map<string, string> {
  return new Map(entries.map((entry) => [entry.id, entry.category]));
}
