allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@helpers4/array@3.1.1'
  - '@helpers4/ci@3.1.1'
  - '@helpers4/color@3.1.1'
  - '@helpers4/commit@3.1.1'
  - '@helpers4/date@3.1.1'
  - '@helpers4/function@3.1.1'
  - '@helpers4/guard@3.1.1'
  - '@helpers4/id@3.1.1'
  - '@helpers4/map@3.1.1'
  - '@helpers4/markdown@3.1.1'
  - '@helpers4/node@3.1.1'
  - '@helpers4/number@3.1.1'
  - '@helpers4/object@3.1.1'
  - '@helpers4/observable@3.1.1'
  - '@helpers4/promise@3.1.1'
  - '@helpers4/set@3.1.1'
  - '@helpers4/string@3.1.1'
  - '@helpers4/structure@3.1.1'
  - '@helpers4/type@3.1.1'
  - '@helpers4/url@3.1.1'
  - '@helpers4/version@3.1.1'
  - helpers4@3.1.1
